import AppleLogo from "./apple-logo.svg"
import GoogleLogo from "./google-logo.svg"
import NokiaLogo from "./nokia-logo.svg"
import SamsungLogo from "./samsung-logo.svg"
import Logo from "./Esim_Direct_Logo.svg"
import HeroBackground from "./heroimg.svg"
import HeroImage from "./Plane_Flying_Over_Map.svg"
import Australia from "./Flags/Australia.png"
import China from "./Flags/China.png"
import Europe from "./Flags/Europe.png"
import USA from "./Flags/USA.png"
import Turkiye from "./Flags/Turkiye.png"
import UnitedKingdom from "./Flags/UnitedKingdom.png"

export { AppleLogo, GoogleLogo, NokiaLogo, SamsungLogo, Logo, HeroBackground, HeroImage, Australia, China, Europe, USA, Turkiye, UnitedKingdom }
